### ISSUE TITLE
Add a permission like: "rvillagerwand.*" to access everything

### ISSUE THREAD

**Issue by ViewShumoon** [r0p3/rVillagerWand#2]
### Permissions
``` YAML
# Includes all other permissions
rvillagerwand.*:
    description: Access everything
    default: op
    children:
        rvillagerwand.aware: true
        rvillagerwand.convertzombie: true
        rvillagerwand.drop: true
        rvillagerwand.follow: true
        rvillagerwand.gethp: true
        rvillagerwand.giveexp: true
        rvillagerwand.givebook: true
        rvillagerwand.glow: true
        rvillagerwand.heal: true
        rvillagerwand.kill: true
        rvillagerwand.newtrades: true
        rvillagerwand.noitemsneeded: true
        rvillagerwand.pickup: true
        rvillagerwand.toggleai: true
        rvillagerwand.toggleinvisible: true
        rvillagerwand.toggleinvulnerable: true
        rvillagerwand.togglepickupitems: true
        rvillagerwand.togglesilent: true
        rvillagerwand.toggletype: true
        rvillagerwand.toggleprofession: true
        rvillagerwand.unemployment: true
        rvillagerwand.wand: true
        rvillagerwand.zombification: true
        rvillagerwand.reload: true
```
