### ISSUE TITLE
Adding localization supports

### ISSUE THREAD

**Issue by ViewShumoon** [r0p3/rVillagerWand#3]
Adding localization supports, then leave the rest to the community like Crowdin or just GitHub~

Love this plugin~
Thanks to the developers for all your hard work.

**Comment by ViewShumoon** [comment]
We should move strings to the "lang" folder instead of "config.yml"  

Here is my translation: 

### zh_cn.yaml
``` YAML
# =================================================================================================#
# CONFIG FOR RVILLAGERWAND
# =================================================================================================#

# Plugin message prefix
Prefix: '&e[&9rVillagerWand&e] &b'

# Title for Villager wand menu
Menu_title: '&c&l村民魔杖 目录'

# Ability to trade with Villagers unlimited amount of times
Unlimitade_trades: false

WAND:
  
  # The name of the wand
  Name: '&6村民魔杖'
  
  # When using /wand and the item the player is holding is incorrect
  # Use {wand} to get the item the wand should be made of
  Wrong_item_message: '&e只有 &a{wand} &e才能被制成魔杖!'
  
  # Set what item to use as a wand
  Item: GOLDEN_HOE
  
  # Set instructions on the wand
  Lore:
  - '&f攻击键 &7⏵ 施展法术'
  - '&f使用键 &7⏵ 打开目录'
  
  # How to display the cost of using a spell
  # Use {item} to get the item name
  # use {cost} to get amount of item needed
  Cost_display:
  - '&e需要消耗品: &a{cost} {item}'

PERMISSION:
  
  # Send player a message if they do not have the required permission to use a spell
  Show_message: true
  
  # Error message to player when trying to use a wand the player doesn"t have the required permission to use
  Message: '&c你没有权限去使用这根魔杖'

NOTENOUGHITEMS:
  
  # Send player a message if the player does not have enough items to use the spell
  Show_message: true
  
  # Message to send to player if they don"t have enough items to use the spell
  Message: '&c你的背包里没有足够的消耗品来施展这个法术'


# Allow a villager to infinitely replenish its trades
Allow_infinite_trades: true


# =================================================================================================#
# DROP INVENTORY
# =================================================================================================#
DROP:
  
  # Wand name
  Name: '&b&l丢弃物品'
  
  # What item to use in the menu
  Icon: HOPPER
  
  # Additional information to display on the wand
  Lore:
  - '&a村民将丢出它的物品'
  
  # If villager has any item in its inventory
  Message: ''
  
  # If Villager doesn't have any item in its inventory
  Empty_inventory_message: '&e物品栏已经是空空的了'
  
  # Allow Villagers to drop there inventory when killed by the wand
  Enable: true

# =================================================================================================#
# FOLLOW
# =================================================================================================#
FOLLOW:
  
  # Wand name
  Name: '&b&l跟随模式'
  
  # What item to use in the menu
  Icon: LEAD
  
  # TODO: A more appropriate translation
  # Additional information to display on the wand
  Lore:
  - '&a切换选中的村民是否跟随你'
  
  # Villager start follow message
  Start_message: 这只村民现在会试着跟着 {player}
  
  # Villager stop follow message
  Stop_message: 这只村民不再跟着你了

# =================================================================================================#
# GET HP
# =================================================================================================#
GETHP: # Use {hp} to get Villager's hp
  
  # Wand name
  Name: '&b&l获取生命值'
  
  # What item to use in the menu
  Icon: RED_WOOL
  
  # Additional information to display on the wand
  Lore:
  - '&a获取村民当前的生命值'
  
  # Message when checking hp
  Message: '&3该村民生命值为: &a{hp}'

# =================================================================================================#
# GIVE EXP
# =================================================================================================#
GIVEEXP:
  
  # Wand name
  Name: '&b&l添加经验'
  
  # What item to use in the menu
  Icon: EXPERIENCE_BOTTLE
  
  # Additional information to display on the wand
  Lore:
  - '&a为村民添加交易经验'
  
  # Use {exp} to get Villager's experience total
  # Message when exp was given to villager
  GiveEXP_message: '{exp}'
  
  # TODO: A more appropriate translation
  # Message when the Villager is the highest level
  HighestEXP_message:  这只村民已经是最高的等级了

  # Message when the Villager is the highest level
  No_proffesion_message: 村民需要一份职业
  
  # Item to pay with for using this spell
  Item: EXPERIENCE_BOTTLE
  
  # Amount of material it cost
  Amount: 1
  
  # Amount of exp to give
  EXP: 32

# =================================================================================================#
# GLOW
# =================================================================================================#
GLOW:
  
  # Wand name
  Name: '&b&l发光模式'
  
  # What item to use in the menu
  Icon: GLOWSTONE
  
  # Additional information to display on the wand
  Lore:
  - '&a让村民发光'
  
  # Message when glow effect is applied
  Start_message: 'DING~'
  
  # Message when glow effect is removed
  Stop_message: ''

# =================================================================================================#
# HEAL
# =================================================================================================#
HEAL:
  
  # Wand name
  Name: '&b&l治愈'
  
  # What item to use in the menu
  Icon: BREAD
  
  # Additional information to display on the wand
  Lore:
  - '&a完全治愈村民'
  
  # When the villager has been fully healed
  Healed_message: '&a这只村民已被治愈'
  
  # If villager already is fully healed
  Already_full_health_message: '&e这只村民很健康, 之前已经被治愈好了'
  
  # Item to pay with for using this spell
  Item: BREAD
  
  # Amount of material it cost
  Amount: 1

# =================================================================================================#
# KILL
# =================================================================================================#
KILL:
  
  # Wand name
  Name: '&b&l消除'
  
  # What item to use in the menu
  Icon: LAVA_BUCKET
  
  # Additional information to display on the wand
  Lore:
  - '&c杀死村民'
  - '&a但不会让别的村民愤怒'
  
  # If this spell should drop Villager's inventory on the ground
  Drop: true
  
  # When villager is killed
  Message: '&c那个可怜的村民完全没有机会逃脱...'

# =================================================================================================#
# NEW TRADE
# =================================================================================================#
NEWTRADES:
  
  # Wand name
  Name: '&b&l新交易'
  
  # What item to use in the menu
  Icon: WRITABLE_BOOK
  
  # TODO: A more appropriate translation
  # Additional information to display on the wand
  Lore:
  - '&e为村民添加交易'
  - '&4只能在从未交易过的村民上生效'
  - '&e将附魔书拿在副手上, 然后村民'
  - '&e就会与你交易那本书'
  # If true only allow Success_message when a Villager is offering an enchanted book
  Only_show_enchanted_books: false
  
  # Message to display the new items the Villager has to offer, use {item} {price}
  Success_message: '&e现在供应&3{item} &e价格为 &a{price}'
  
  # Message if Villager has a profession and has not been traded with
  Fail_message: '&c这个法术只有在村民具有职业并且没有被交易过时才能生效!'

# =================================================================================================#
# PICK UP
# =================================================================================================#
PICKUP:
  
  # Wand name
  Name: '&b&l打包'
  
  # What item to use in the menu
  Icon: VILLAGER_SPAWN_EGG
  
  # Additional information to display on the wand
  Lore:
  - '&e将村民打包回&6刷怪蛋'
  
  # Message when villager is turned into a spawn egg
  Message: ''
  
  # Message when villager is not an adult
  Not_adult_message: '&c你只能打包成年村民'
  
  # Message if villager has a profession
  Has_profession_message: '&c你只能打包没有职业的村民'

# =================================================================================================#
# AI
# =================================================================================================#
TOGGLEAI:
  
  # Wand name
  Name: '&b&l启用AI'
  
  # What item to use in the menu
  Icon: ENCHANTED_BOOK
  
  # Additional information to display on the wand
  Lore:
  - '&5切换村民是否有&cAI'
  
  # Message when AI is turned on
  On_message: ''
  
  # Message when AI is turned off
  Off_message: ''

# =================================================================================================#
# AWARENESS
# =================================================================================================#
AWARE:
  
  # Wand name
  Name: '&b&l切换意识'
  
  # What item to use in the menu
  Icon: CARVED_PUMPKIN
  
  # Additional information to display on the wand
  Lore:
  - '&5切换村民是否有&c意识'
  - '&5无意识的村民意味着不会自主移动'
  
  # Message when awareness is turned on
  On_message: '&e这只村民的意识已&a启用'
  
  # Message when awareness is turned off
  Off_message: '&e这只村民的意识已&c禁用'

# =================================================================================================#
# INVISIBILITY
# =================================================================================================#
TOGGLEINVISIBILITY:
  
  # Wand name
  Name: '&b&l隐身模式'
  
  # What item to use in the menu
  Icon: GOLDEN_CARROT
  
  # Additional information to display on the wandc
  Lore:
  - '&5切换村民是否&c隐身'
  
  # Message when villager is set to invisible
  Is_invisible_message: ''
  
  # Message when villager is set to visible
  Is_visible_message: ''

# =================================================================================================#
# INVULNERABLE
# =================================================================================================#
TOGGLEINVULNERABLE:
  
  # Wand name
  Name: '&b&l无敌模式'
  
  # What item to use in the menu
  Icon: BEDROCK
  
  # Additional information to display on the wand
  Lore:
  - '&5切换村民是否是无敌的'
  - '&c这将会使魔杖不再对这只村民生效'
  - '&c创造模式除外'
  
  # Message when villager is set to invulnerable
  Invulnerable_message: ''
  
  # Message when villager is set to vulnerable
  Vulnerable_message: ''

# =================================================================================================#
# PICK UP ITEMS
# =================================================================================================#
TOGGLEPICKUPITEMS:
  
  # Wand name
  Name: '&b&l切换物品拾取'
  
  # What item to use in the menu
  Icon: CHEST
  
  # Additional information to display on the wand
  Lore:
  - '&a切换村民能否捡起物品'
  
  # Message when pick up is turned on
  Pickup_on_message: ''
  
  # Message when pick up is turned off
  Pickup_off_message: ''

# =================================================================================================#
# SILENCE
# =================================================================================================#
TOGGLEMUTE:
  
  # Wand name
  Name: '&b&l静音'
  
  # What item to use in the menu
  Icon: WHITE_WOOL
  
  # Additional information to display on the wand
  Lore:
  - '&5切换村民能否发出声音'
  
  # Message when villager is muted
  Muted_message: '&e村民现在被&c静音&e了'
  
  # Message when villager is unmuted
  Unmuted_message: '&e村民现在被&a解除静音&e了'

# =================================================================================================#
# CHANGE CLOTHES
# =================================================================================================#
TOGGLECLOTHES: # Use {type} to get villager type
  
  # Wand name
  Name: '&b&l更换皮肤'
  
  # What item to use in the menu
  Icon: CHAINMAIL_CHESTPLATE
  
  # Additional information to display on the wand
  Lore:
  - '&5更换村民的皮肤服装'
  
  # Message when changing clothes
  # Use {type} to get the new Villager type
  Message: ''

# =================================================================================================#
# TOGGLE PROFESSION
# =================================================================================================#
TOGGLEPROFESSION: # Use {type} to get villager type
  
  # Wand name
  Name: '&b&l改变职业'
  
  # What item to use in the menu
  Icon: BOOK
  
  # Additional information to display on the wand
  Lore:
  - '&5更改村民的职业'
  - '&5只会对拥有工作方块'
  - '&5的村民生效'
  
  # Message when changing clothes
  # Use {type} to get the new Villager type
  Message: ''

# =================================================================================================#
# UNEMPLOYMENT
# =================================================================================================#
UNEMPLOYMENT:
  
  # Wand name
  Name: '&b&l解雇村民'
  
  # What item to use in the menu
  Icon: CHAINMAIL_BOOTS
  
  # Additional information to display on the wand
  Lore:
  - '&c移除村民的交易经验和职业'
  
  # Message when Villager is unemployed
  Success_message: '&a这只村民现在失业了'
  
  # Message when Villager has experience
  Failed_message: '&c这只村民已经是失业状态'

# =================================================================================================#
# TURN ZOMBIFIED VILLAGER INTO VILLAGER
# =================================================================================================#
ZOMBIETOVILLAGER:
  
  # Wand name
  Name: '&b&l治疗僵尸村民'
  
  # What item to use in the menu
  Icon: GOLDEN_APPLE
  
  # Additional information to display on the wand
  Lore:
  - '&e将&c僵尸村民&e治愈, 变回&a村民'
  
  # Message when converting a Zombiefied Villager into a Villager
  Message: ''
  
  # Item to pay with for using this spell
  Item: GOLDEN_APPLE
  
  # Amount of material it cost
  Amount: 1

# =================================================================================================#
# TURN VILLAGER INTO ZOMBIFIED VILLAGER
# =================================================================================================#
VILLAGERTOZOMBIE:
  
  # Wand name
  Name: '&b&l感染村民'
  
  # What item to use in the menu
  Icon: ZOMBIE_HEAD
  
  # Additional information to display on the wand
  Lore:
  - '&e将&a村民&e感染成&c僵尸村民'
  
  # Message when converting a villager into a Zombiefied Villager
  Success_message: ''
  
  # Message if Villager isn't an adult
  Fail_message: '&c你只能将成年村民变成僵尸村民'
  
  # Item to pay with for using this spell
  Item: ROTTEN_FLESH
  
  # Amount of material it cost
  Amount: 1

# =================================================================================================#
# ITEM/CHAT FORMAT (CHEAT SHEET)
# =================================================================================================#

# CHATCOLOR CODES
# &0 Black
# &1 Dark Blue
# &2 Dark Green
# &3 Dark Aqua
# &4 Dark Red
# &5 Dark Purple
# &6 Gold
# &7 Gray
# &8 Dark Gray
# &9 Blue
# &a Green
# &b Aqua
# &c Red
# &d Light Purple
# &e Yellow
# &f White

# ##############################################################
# IF USING THESE MAKE SURE TO USE ALWAYS USE COLOR BEFORE
# THIS WORKS &b&l
# THIS DOES NOT WORK &l&b
# ##############################################################
# &k Obfuscated
# &l Bold
# &m Strikethrough
# &n Underline
# &o Italic
# &r Reset the default color

```
    
PS:
  In line 143, the description for "No_proffesion_message" is wrong, maybe "Message when the Villager has no proffesion"?
``` YAML
143      # Message when the Villager is the highest level
144      No_proffesion_message: The Villager needs to have a profession
```
